---
user_name: juser
user_password_crypted: "$6$khprmotoVWYLZY2W$Gj5Y6p4R.LsXQdL2xf6umhInzZ9GCG6USXB0XIl86m5.IbqSOPXJ0mxVUE7y5kGFE/arHgExAxoz0kEULiplZ."

autologin: True

publisher: ndv
org: ps1
show: JennieTV

time_zone: US/Central

frequency: 60

# domain:

apt_proxy: true

# apt.enable_oldstable: true

staticips:
  write_hosts: false
  write_interfaces: false
  hosts: []

# Git repos:
playbook_repo: https://salsa.debian.org/debconf-video-team/ansible
# playbook_repo: https://github.com/CarlFK/video-stack-deploy.git
playbook_branch: master

inventory_repo: https://github.com/CarlFK/video-stack-inventory.git
inventory_repo_dir: cboxs

voctomix:
  display_system: x
  previews: false
  mirrors: false
  framerate: 30
  autostart_gui: false

# streaming: null

serial_terminal:
    #- flterm
- cu
- tio

sources:
- Camera1
- Camera2
- Camera3

rsync_excludes:
- 0[0-7]*.ts
- 0[0-7]*.ts.mp4
- 0[0-7]*.ts.wav.png
- 2*.ts
- 2*.ts.mp4
- 2*.ts.wav.png

# what the pxe server can install
ubuntu_suites: [trusty, xenial, artful, bionic, cosmic]

veyepar_url: http://veyepar.nextdayvideo.com

