# inventory/host_vars/edge.yml

dnsmasq__bind_interfaces: False

# wifi is connection to the venu internet
dnsmasq__upstream_interfaces: ['wlp8s0b1',]

# pxe machines will be connected to wired port
dnsmasq__interfaces:
 - interface: 'enp0s25'

# eth_uplink_mac_address: ac:81:12:3a:16:b0  # wifi
eth_uplink_mac_address: 80:3f:5d:08:c3:9d # usb rubberband

eth_local_mac_address: f0:de:f1:77:21:73  # wired
eth_local_ip_address: 10.42.0.2
dhcp_range: 10.20.0.128,10.20.0.254,6h
eth_local_ip_gateway: 10.42.0.1 # twist uplink

# what the pxe server can install
# ubuntu_suites: [trusty, xenial, zesty, artful]
ubuntu_suites: [xenial, zesty, artful]
