---
blackmagic_sources:
- card: 0
  connection: SDI
  audio: true
  mode: 17
sources:
- Cam1
- Cam2
- GrabberL
- GrabberR

room_name: greathall
irc_room_channel: "#lca2018-greathall"
irc_nick: lcaav_greathall
