---
blackmagic:
  desktopvideo: http://edge/bm/Blackmagic_Desktop_Video_Linux_10.9.10/deb/x86_64/desktopvideo_10.9.10a2_amd64.deb
  desktopvideo_gui: http://edge/bm/Blackmagic_Desktop_Video_Linux_10.9.10/deb/x86_64/desktopvideo-gui_10.9.10a2_amd64.deb
#  mediaexpress: http://edge/bm/Blackmagic_Desktop_Video_Linux_10.9.10/deb/x86_64/mediaexpress_3.5.4a5_amd64.deb
  dkms_version: 10.9.10a2

blackmagic_sources:
- card: 0
  connection: SDI
  audio: true
  mode: 17
sources:
- Cam1
- Cam2
- GrabberL
- GrabberR

room_name: greathall
irc_room_channel: "#lca2018-greathall"
irc_nick: lcaav_greathall
