eth_uplink_mac_address: 60:67:20:ed:00:e4 # wifi

eth_local_mac_address: 3c:97:0e:53:ce:07 # wired
eth_local_ip_address: 10.20.0.3
dhcp_range: 10.40.0.128,10.40.0.254,6h
# eth_local_ip_gateway: 10.42.0.1 # twist uplink
