---
user_name: juser
user_password_crypted: "$6$khprmotoVWYLZY2W$Gj5Y6p4R.LsXQdL2xf6umhInzZ9GCG6USXB0XIl86m5.IbqSOPXJ0mxVUE7y5kGFE/arHgExAxoz0kEULiplZ."

autologin: True

publisher: ndv
org: koya_law
show: isda_4

time_zone: US/Central

domain: private.lan

# Git repos:
# playbook_repo: https://anonscm.debian.org/cgit/debconf-video/ansible.git
playbook_repo: https://salsa.debian.org/debconf-video-team/ansible
playbook_branch: master

# To replace the stock inventory with your own, point at your own github repo

inventory_repo: https://github.com/CarlFK/video-stack-inventory.git
inventory_branch: master

veyepar_url: http://veyepar.nextdayvideo.com

blackmagic:
    urls:
    - desktopvideo: http://pc8/bm/Blackmagic_Desktop_Video_Linux_10.11.1/deb/x86_64/desktopvideo_10.11.1a4_amd64.deb
    # - desktopvideo_gui: http://pc8/bm/Blackmagic_Desktop_Video_Linux_10.11.1/deb/x86_64/desktopvideo-gui_10.11.1a4_amd64.deb
    - mediaexpress: http://pc8/bm/Blackmagic_Desktop_Video_Linux_10.11.1/deb/x86_64/mediaexpress_3.5.6a2_amd64.deb
    dkms_version: 10.11.1a4

voctomix:
  display_system: x
  framerate: 30

frequency: 60

videodisplay:
  system: x

# streaming: null

serial_terminal:
- tio

sources:
- Camera
- Grabber

rsync_excludes:
- 0[0-7]*.ts
- 0[0-7]*.ts.mp4
- 0[0-7]*.ts.wav.png
- 2*.ts
- 2*.ts.mp4
- 2*.ts.wav.png
