---
user_name: juser
user_password_crypted: "$6$khprmotoVWYLZY2W$Gj5Y6p4R.LsXQdL2xf6umhInzZ9GCG6USXB0XIl86m5.IbqSOPXJ0mxVUE7y5kGFE/arHgExAxoz0kEULiplZ."
autologin: True

publisher: ndv
org: nbpy
show: nbpy18
room: mystic

time_zone: US/Pacific

domain: private.lan

# distro: Debian
# debian_version: stretch

apt_proxy: true

# Git repos:
# playbook_repo: https://salsa.debian.org/debconf-video-team/ansible.git
# playbook_repo: https://github.com/CarlFK/video-stack-deploy.git
# playbook_branch: master

# To replace the stock inventory with your own, point at your own github repo
inventory_repo: https://github.com/CarlFK/video-stack-inventory.git
inventory_dir: nbpy18

frequency: 50
voctomix:
  display_system: x # gl
  framerate: 30
#  loop_url: http://go/video/pyconza-loop.ts
#  bgloop_url: http://go/video/pyconza-bgloop.ts

blackmagic:
  urls:
  - desktopvideo: http://pc8/bm/Blackmagic_Desktop_Video_Linux_10.11.2/deb/x86_64/desktopvideo_10.11.2a3_amd64.deb
  - desktopvideo_gui: http://pc8/bm/Blackmagic_Desktop_Video_Linux_10.11.2/deb/x86_64/desktopvideo-gui_10.11.2a3_amd64.deb
  - mediaexpress: http://pc8/bm/Blackmagic_Desktop_Video_Linux_10.11.2/deb/x86_64/mediaexpress_3.5.6a2_amd64.deb
  dkms_version: 10.11.2a3

irc:
  autostart: false
  network: freenode
  server: irc.freenode.net
  ssl_port: 6697
  global_channels:
  - "#nbpy"

sources:
- Camera
- Grabber

rsync_excludes:
- 0[0-7]*.ts
- 0[0-7]*.ts.mp4
- 0[0-7]*.ts.wav.png
- 2*.ts
- 2*.ts.mp4
- 2*.ts.wav.png

# veyepar_url: http://veyepar.nextdayvideo.com
