---
room_name:  mystic

# eth_local_mac_address: c8:60:00:6a:13:bd
static_ip: 10.42.0.10
domain: private.lan

video_disk: /dev/sda1

blackmagic_sources:
# Panasonic
- card: 0
  connection: HDMI
  mode: 18
  audio: true

# Mini JVC, audio from usb audio dongle
# - card: 1
#   connection: HDMI
#   audio: true
#   mode: 18
#   alsa_device: hw:1,0
#  audio_delay: 1000

sources:
- JVC
- Grabber
  # - Everio
