# inventory/host_vars/dc10b.yml

dnsmasq__bind_interfaces: False

# wifi is connection to the venu internet
# dnsmasq__upstream_interfaces: ['wlo1',]

# pxe machines will be connected to wired port
dnsmasq__interfaces:
 - interface: 'enp0s25'

eth_local_mac_address: b4:99:ba:e9:5c:5c  # dc10b wired
eth_local_ip_address: 10.42.0.2
dhcp_range: 10.20.0.128,10.20.0.254,6h
eth_local_ip_gateway: 10.42.0.1 # twist uplink

# what the pxe server can install
# ubuntu_suites: [trusty, xenial, zesty, artful]
ubuntu_suites: []

# static_ip: 10.42.0.12
voctomix:
  host: 10.42.0.10
  port: 10001
