---
user_name: juser
user_password_crypted: "$6$khprmotoVWYLZY2W$Gj5Y6p4R.LsXQdL2xf6umhInzZ9GCG6USXB0XIl86m5.IbqSOPXJ0mxVUE7y5kGFE/arHgExAxoz0kEULiplZ."

autologin: True

publisher: ndv
org: croud_supply
show: teardown_portland_2018

time_zone: US/Pasific

domain: private.lan
# debian_version: stretch

staticips.write_hosts: False
staticips.write_interfaces: False

apt_proxy: true

# Git repos:
playbook_repo: https://salsa.debian.org/debconf-video-team/ansible
playbook_branch: master

# To replace the stock inventory with your own, point at your own github repo

inventory_repo: https://github.com/CarlFK/video-stack-inventory.git
inventory_branch: master

veyepar_url: http://veyepar.nextdayvideo.com

blackmagic:
  desktopvideo: http://10.42.0.1:8007/bm/Blackmagic_Desktop_Video_Linux_10.9.12/deb/x86_64/desktopvideo_10.9.12a3_amd64.deb
#  desktopvideo_gui: http://pc8/bm/Blackmagic_Desktop_Video_Linux_10.9.11/deb/x86_64/desktopvideo-gui_10.9.11a2_amd64.deb
  mediaexpress: http://10.42.0.1:8007/bm/Blackmagic_Desktop_Video_Linux_10.9.12/deb/x86_64/mediaexpress_3.5.5a1_amd64.deb
  dkms_version: 10.9.12a3

videodisplay:
  system: x

# streaming: null

serial_terminal:
    #- flterm
    # - cu
- minicom
- tio

sources:
- Camera
- Grabber

rsync_excludes:
- 0[0-7]*.ts
- 0[0-7]*.ts.mp4
- 0[0-7]*.ts.wav.png
- 2*.ts
- 2*.ts.mp4
- 2*.ts.wav.png
