---
user_name: juser
user_password_crypted: "$6$khprmotoVWYLZY2W$Gj5Y6p4R.LsXQdL2xf6umhInzZ9GCG6USXB0XIl86m5.IbqSOPXJ0mxVUE7y5kGFE/arHgExAxoz0kEULiplZ."

autologin: True

conference_name: LCA
conference_town: Sydney
conference_country: Australia

org: lca
show: lca2018

time_zone: Australia/Sydney

domain: private.lan

distro: Debian
debian_version: stretch
enable_sid: false
enable_oldstable: true

debian_host: ftp.au.debian.org
ubuntu_host: au.archive.ubuntu.com
debian_suites: [stretch]
ubuntu_sites: [xenial, zesty, artful]

apt_proxy: true

# Git repos:
playbook_repo: https://salsa.debian.org/debconf-video-team/ansible
playbook_branch: master

# To replace the stock inventory with your own, point at your own github repo
inventory_repo: https://github.com/CarlFK/video-stack-inventory.git
inventory_branch: master

blackmagic:
  desktopvideo: http://edge/bm/Blackmagic_Desktop_Video_Linux_10.9.10a2/deb/amd64/desktopvideo_10.9.10a2_amd64.deb
  desktopvideo_gui: http://edge/bm/Blackmagic_Desktop_Video_Linux_10.9.10a2/deb/amd64/desktopvideo-gui_10.9.10a2_amd64.deb
#  mediaexpress: http://edge/bm/Blackmagic_Desktop_Video_Linux_10.9.10a2/deb/amd64/mediaexpress_3.5.4a5.deb
  dkms_version: 10.9.10a2

serial_terminal:
- tio
- minicom

sources:
- Camera
- Grabber

# Late night, early morning
rsync_excludes:
- 0[0-7]*.ts
- 0[0-7]*.ts.mp4
- 0[0-7]*.ts.wav.png
- 2*.ts
- 2*.ts.mp4
- 2*.ts.wav.png

# Carl's Branch only:
publisher: ndv
